# Generated by Django 5.0.7 on 2026-07-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('number', models.CharField(max_length=32)),
                ('icon', models.CharField(default='B', max_length=8)),
                ('bg', models.CharField(default='#f1e8f8', max_length=32)),
                ('fg', models.CharField(default='#2a0b46', max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['display_order', 'bank'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=64)),
                ('wifi_ssid', models.CharField(max_length=120)),
                ('ip', models.CharField(max_length=64)),
                ('wifi', models.BooleanField(default=True)),
                ('online', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('last_seen', models.CharField(default='just now', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=64)),
                ('price', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('order', models.CharField(max_length=64)),
                ('customer', models.CharField(max_length=120)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('method', models.CharField(max_length=64)),
                ('account', models.CharField(max_length=32)),
                ('status', models.CharField(default='Pending Confirmation', max_length=64)),
                ('date', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=64)),
                ('price', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
